// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package bridge

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AddRelayer is the `addRelayer` instruction.
type AddRelayer struct {
	Relayer *RelayerDetails

	// [0] = [WRITE, SIGNER] adminAuthority
	//
	// [1] = [WRITE] bridgeSettings
	//
	// [2] = [WRITE] relayerSettings
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAddRelayerInstructionBuilder creates a new `AddRelayer` instruction builder.
func NewAddRelayerInstructionBuilder() *AddRelayer {
	nd := &AddRelayer{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetRelayer sets the "relayer" parameter.
func (inst *AddRelayer) SetRelayer(relayer RelayerDetails) *AddRelayer {
	inst.Relayer = &relayer
	return inst
}

// SetAdminAuthorityAccount sets the "adminAuthority" account.
func (inst *AddRelayer) SetAdminAuthorityAccount(adminAuthority ag_solanago.PublicKey) *AddRelayer {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(adminAuthority).WRITE().SIGNER()
	return inst
}

// GetAdminAuthorityAccount gets the "adminAuthority" account.
func (inst *AddRelayer) GetAdminAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetBridgeSettingsAccount sets the "bridgeSettings" account.
func (inst *AddRelayer) SetBridgeSettingsAccount(bridgeSettings ag_solanago.PublicKey) *AddRelayer {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(bridgeSettings).WRITE()
	return inst
}

// GetBridgeSettingsAccount gets the "bridgeSettings" account.
func (inst *AddRelayer) GetBridgeSettingsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetRelayerSettingsAccount sets the "relayerSettings" account.
func (inst *AddRelayer) SetRelayerSettingsAccount(relayerSettings ag_solanago.PublicKey) *AddRelayer {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(relayerSettings).WRITE()
	return inst
}

// GetRelayerSettingsAccount gets the "relayerSettings" account.
func (inst *AddRelayer) GetRelayerSettingsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *AddRelayer) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *AddRelayer {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *AddRelayer) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst AddRelayer) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AddRelayer,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AddRelayer) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AddRelayer) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Relayer == nil {
			return errors.New("Relayer parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.AdminAuthority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.BridgeSettings is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.RelayerSettings is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *AddRelayer) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AddRelayer")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Relayer", *inst.Relayer))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" adminAuthority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" bridgeSettings", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("relayerSettings", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("  systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj AddRelayer) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Relayer` param:
	err = encoder.Encode(obj.Relayer)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AddRelayer) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Relayer`:
	err = decoder.Decode(&obj.Relayer)
	if err != nil {
		return err
	}
	return nil
}

// NewAddRelayerInstruction declares a new AddRelayer instruction with the provided parameters and accounts.
func NewAddRelayerInstruction(
	// Parameters:
	relayer RelayerDetails,
	// Accounts:
	adminAuthority ag_solanago.PublicKey,
	bridgeSettings ag_solanago.PublicKey,
	relayerSettings ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *AddRelayer {
	return NewAddRelayerInstructionBuilder().
		SetRelayer(relayer).
		SetAdminAuthorityAccount(adminAuthority).
		SetBridgeSettingsAccount(bridgeSettings).
		SetRelayerSettingsAccount(relayerSettings).
		SetSystemProgramAccount(systemProgram)
}
