// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package bridge

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// InitializeSettings is the `initializeSettings` instruction.
type InitializeSettings struct {
	AdminAuthority *ag_solanago.PublicKey
	Relayers       *[]RelayerDetails
	Quorum         *uint32

	// [0] = [WRITE, SIGNER] signer
	//
	// [1] = [WRITE] bridgeSettings
	//
	// [2] = [WRITE] relayerSettings
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewInitializeSettingsInstructionBuilder creates a new `InitializeSettings` instruction builder.
func NewInitializeSettingsInstructionBuilder() *InitializeSettings {
	nd := &InitializeSettings{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetAdminAuthority sets the "adminAuthority" parameter.
func (inst *InitializeSettings) SetAdminAuthority(adminAuthority ag_solanago.PublicKey) *InitializeSettings {
	inst.AdminAuthority = &adminAuthority
	return inst
}

// SetRelayers sets the "relayers" parameter.
func (inst *InitializeSettings) SetRelayers(relayers []RelayerDetails) *InitializeSettings {
	inst.Relayers = &relayers
	return inst
}

// SetQuorum sets the "quorum" parameter.
func (inst *InitializeSettings) SetQuorum(quorum uint32) *InitializeSettings {
	inst.Quorum = &quorum
	return inst
}

// SetSignerAccount sets the "signer" account.
func (inst *InitializeSettings) SetSignerAccount(signer ag_solanago.PublicKey) *InitializeSettings {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *InitializeSettings) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetBridgeSettingsAccount sets the "bridgeSettings" account.
func (inst *InitializeSettings) SetBridgeSettingsAccount(bridgeSettings ag_solanago.PublicKey) *InitializeSettings {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(bridgeSettings).WRITE()
	return inst
}

// GetBridgeSettingsAccount gets the "bridgeSettings" account.
func (inst *InitializeSettings) GetBridgeSettingsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetRelayerSettingsAccount sets the "relayerSettings" account.
func (inst *InitializeSettings) SetRelayerSettingsAccount(relayerSettings ag_solanago.PublicKey) *InitializeSettings {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(relayerSettings).WRITE()
	return inst
}

// GetRelayerSettingsAccount gets the "relayerSettings" account.
func (inst *InitializeSettings) GetRelayerSettingsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *InitializeSettings) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *InitializeSettings {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *InitializeSettings) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst InitializeSettings) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_InitializeSettings,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst InitializeSettings) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *InitializeSettings) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.AdminAuthority == nil {
			return errors.New("AdminAuthority parameter is not set")
		}
		if inst.Relayers == nil {
			return errors.New("Relayers parameter is not set")
		}
		if inst.Quorum == nil {
			return errors.New("Quorum parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.BridgeSettings is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.RelayerSettings is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *InitializeSettings) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("InitializeSettings")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("AdminAuthority", *inst.AdminAuthority))
						paramsBranch.Child(ag_format.Param("      Relayers", *inst.Relayers))
						paramsBranch.Child(ag_format.Param("        Quorum", *inst.Quorum))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         signer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" bridgeSettings", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("relayerSettings", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("  systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj InitializeSettings) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `AdminAuthority` param:
	err = encoder.Encode(obj.AdminAuthority)
	if err != nil {
		return err
	}
	// Serialize `Relayers` param:
	err = encoder.Encode(obj.Relayers)
	if err != nil {
		return err
	}
	// Serialize `Quorum` param:
	err = encoder.Encode(obj.Quorum)
	if err != nil {
		return err
	}
	return nil
}
func (obj *InitializeSettings) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `AdminAuthority`:
	err = decoder.Decode(&obj.AdminAuthority)
	if err != nil {
		return err
	}
	// Deserialize `Relayers`:
	err = decoder.Decode(&obj.Relayers)
	if err != nil {
		return err
	}
	// Deserialize `Quorum`:
	err = decoder.Decode(&obj.Quorum)
	if err != nil {
		return err
	}
	return nil
}

// NewInitializeSettingsInstruction declares a new InitializeSettings instruction with the provided parameters and accounts.
func NewInitializeSettingsInstruction(
	// Parameters:
	adminAuthority ag_solanago.PublicKey,
	relayers []RelayerDetails,
	quorum uint32,
	// Accounts:
	signer ag_solanago.PublicKey,
	bridgeSettings ag_solanago.PublicKey,
	relayerSettings ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *InitializeSettings {
	return NewInitializeSettingsInstructionBuilder().
		SetAdminAuthority(adminAuthority).
		SetRelayers(relayers).
		SetQuorum(quorum).
		SetSignerAccount(signer).
		SetBridgeSettingsAccount(bridgeSettings).
		SetRelayerSettingsAccount(relayerSettings).
		SetSystemProgramAccount(systemProgram)
}
