// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package bridge

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Pause is the `pause` instruction.
type Pause struct {

	// [0] = [WRITE, SIGNER] adminAuthority
	//
	// [1] = [WRITE] bridgeSettings
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewPauseInstructionBuilder creates a new `Pause` instruction builder.
func NewPauseInstructionBuilder() *Pause {
	nd := &Pause{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetAdminAuthorityAccount sets the "adminAuthority" account.
func (inst *Pause) SetAdminAuthorityAccount(adminAuthority ag_solanago.PublicKey) *Pause {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(adminAuthority).WRITE().SIGNER()
	return inst
}

// GetAdminAuthorityAccount gets the "adminAuthority" account.
func (inst *Pause) GetAdminAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetBridgeSettingsAccount sets the "bridgeSettings" account.
func (inst *Pause) SetBridgeSettingsAccount(bridgeSettings ag_solanago.PublicKey) *Pause {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(bridgeSettings).WRITE()
	return inst
}

// GetBridgeSettingsAccount gets the "bridgeSettings" account.
func (inst *Pause) GetBridgeSettingsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst Pause) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Pause,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Pause) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Pause) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.AdminAuthority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.BridgeSettings is not set")
		}
	}
	return nil
}

func (inst *Pause) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Pause")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("adminAuthority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("bridgeSettings", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj Pause) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *Pause) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewPauseInstruction declares a new Pause instruction with the provided parameters and accounts.
func NewPauseInstruction(
	// Accounts:
	adminAuthority ag_solanago.PublicKey,
	bridgeSettings ag_solanago.PublicKey) *Pause {
	return NewPauseInstructionBuilder().
		SetAdminAuthorityAccount(adminAuthority).
		SetBridgeSettingsAccount(bridgeSettings)
}
