// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package bridge

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RenounceRelayer is the `renounceRelayer` instruction.
type RenounceRelayer struct {

	// [0] = [WRITE, SIGNER] relayer
	//
	// [1] = [WRITE] relayerSettings
	//
	// [2] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRenounceRelayerInstructionBuilder creates a new `RenounceRelayer` instruction builder.
func NewRenounceRelayerInstructionBuilder() *RenounceRelayer {
	nd := &RenounceRelayer{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetRelayerAccount sets the "relayer" account.
func (inst *RenounceRelayer) SetRelayerAccount(relayer ag_solanago.PublicKey) *RenounceRelayer {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(relayer).WRITE().SIGNER()
	return inst
}

// GetRelayerAccount gets the "relayer" account.
func (inst *RenounceRelayer) GetRelayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetRelayerSettingsAccount sets the "relayerSettings" account.
func (inst *RenounceRelayer) SetRelayerSettingsAccount(relayerSettings ag_solanago.PublicKey) *RenounceRelayer {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(relayerSettings).WRITE()
	return inst
}

// GetRelayerSettingsAccount gets the "relayerSettings" account.
func (inst *RenounceRelayer) GetRelayerSettingsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *RenounceRelayer) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *RenounceRelayer {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *RenounceRelayer) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst RenounceRelayer) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RenounceRelayer,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RenounceRelayer) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RenounceRelayer) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Relayer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.RelayerSettings is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *RenounceRelayer) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RenounceRelayer")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("        relayer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("relayerSettings", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("  systemProgram", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj RenounceRelayer) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *RenounceRelayer) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewRenounceRelayerInstruction declares a new RenounceRelayer instruction with the provided parameters and accounts.
func NewRenounceRelayerInstruction(
	// Accounts:
	relayer ag_solanago.PublicKey,
	relayerSettings ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *RenounceRelayer {
	return NewRenounceRelayerInstructionBuilder().
		SetRelayerAccount(relayer).
		SetRelayerSettingsAccount(relayerSettings).
		SetSystemProgramAccount(systemProgram)
}
