// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package bridge

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetQuorum is the `setQuorum` instruction.
type SetQuorum struct {
	Quorum *uint32

	// [0] = [WRITE, SIGNER] adminAuthority
	//
	// [1] = [WRITE] bridgeSettings
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetQuorumInstructionBuilder creates a new `SetQuorum` instruction builder.
func NewSetQuorumInstructionBuilder() *SetQuorum {
	nd := &SetQuorum{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetQuorum sets the "quorum" parameter.
func (inst *SetQuorum) SetQuorum(quorum uint32) *SetQuorum {
	inst.Quorum = &quorum
	return inst
}

// SetAdminAuthorityAccount sets the "adminAuthority" account.
func (inst *SetQuorum) SetAdminAuthorityAccount(adminAuthority ag_solanago.PublicKey) *SetQuorum {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(adminAuthority).WRITE().SIGNER()
	return inst
}

// GetAdminAuthorityAccount gets the "adminAuthority" account.
func (inst *SetQuorum) GetAdminAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetBridgeSettingsAccount sets the "bridgeSettings" account.
func (inst *SetQuorum) SetBridgeSettingsAccount(bridgeSettings ag_solanago.PublicKey) *SetQuorum {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(bridgeSettings).WRITE()
	return inst
}

// GetBridgeSettingsAccount gets the "bridgeSettings" account.
func (inst *SetQuorum) GetBridgeSettingsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst SetQuorum) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetQuorum,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetQuorum) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetQuorum) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Quorum == nil {
			return errors.New("Quorum parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.AdminAuthority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.BridgeSettings is not set")
		}
	}
	return nil
}

func (inst *SetQuorum) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetQuorum")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Quorum", *inst.Quorum))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("adminAuthority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("bridgeSettings", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj SetQuorum) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Quorum` param:
	err = encoder.Encode(obj.Quorum)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetQuorum) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Quorum`:
	err = decoder.Decode(&obj.Quorum)
	if err != nil {
		return err
	}
	return nil
}

// NewSetQuorumInstruction declares a new SetQuorum instruction with the provided parameters and accounts.
func NewSetQuorumInstruction(
	// Parameters:
	quorum uint32,
	// Accounts:
	adminAuthority ag_solanago.PublicKey,
	bridgeSettings ag_solanago.PublicKey) *SetQuorum {
	return NewSetQuorumInstructionBuilder().
		SetQuorum(quorum).
		SetAdminAuthorityAccount(adminAuthority).
		SetBridgeSettingsAccount(bridgeSettings)
}
