// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package tokens_safe

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// BridgeTransfer is the `bridgeTransfer` instruction.
type BridgeTransfer struct {
	Amount *uint64

	// [0] = [WRITE, SIGNER] bridgeAuthority
	//
	// [1] = [WRITE] safeSettings
	//
	// [2] = [WRITE] tokenMint
	//
	// [3] = [WRITE] whitelistedToken
	//
	// [4] = [WRITE] sendFrom
	//
	// [5] = [WRITE] sendTo
	//
	// [6] = [] recipient
	//
	// [7] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewBridgeTransferInstructionBuilder creates a new `BridgeTransfer` instruction builder.
func NewBridgeTransferInstructionBuilder() *BridgeTransfer {
	nd := &BridgeTransfer{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	return nd
}

// SetAmount sets the "amount" parameter.
func (inst *BridgeTransfer) SetAmount(amount uint64) *BridgeTransfer {
	inst.Amount = &amount
	return inst
}

// SetBridgeAuthorityAccount sets the "bridgeAuthority" account.
func (inst *BridgeTransfer) SetBridgeAuthorityAccount(bridgeAuthority ag_solanago.PublicKey) *BridgeTransfer {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(bridgeAuthority).WRITE().SIGNER()
	return inst
}

// GetBridgeAuthorityAccount gets the "bridgeAuthority" account.
func (inst *BridgeTransfer) GetBridgeAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSafeSettingsAccount sets the "safeSettings" account.
func (inst *BridgeTransfer) SetSafeSettingsAccount(safeSettings ag_solanago.PublicKey) *BridgeTransfer {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(safeSettings).WRITE()
	return inst
}

// GetSafeSettingsAccount gets the "safeSettings" account.
func (inst *BridgeTransfer) GetSafeSettingsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetTokenMintAccount sets the "tokenMint" account.
func (inst *BridgeTransfer) SetTokenMintAccount(tokenMint ag_solanago.PublicKey) *BridgeTransfer {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(tokenMint).WRITE()
	return inst
}

// GetTokenMintAccount gets the "tokenMint" account.
func (inst *BridgeTransfer) GetTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetWhitelistedTokenAccount sets the "whitelistedToken" account.
func (inst *BridgeTransfer) SetWhitelistedTokenAccount(whitelistedToken ag_solanago.PublicKey) *BridgeTransfer {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(whitelistedToken).WRITE()
	return inst
}

// GetWhitelistedTokenAccount gets the "whitelistedToken" account.
func (inst *BridgeTransfer) GetWhitelistedTokenAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSendFromAccount sets the "sendFrom" account.
func (inst *BridgeTransfer) SetSendFromAccount(sendFrom ag_solanago.PublicKey) *BridgeTransfer {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(sendFrom).WRITE()
	return inst
}

// GetSendFromAccount gets the "sendFrom" account.
func (inst *BridgeTransfer) GetSendFromAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSendToAccount sets the "sendTo" account.
func (inst *BridgeTransfer) SetSendToAccount(sendTo ag_solanago.PublicKey) *BridgeTransfer {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(sendTo).WRITE()
	return inst
}

// GetSendToAccount gets the "sendTo" account.
func (inst *BridgeTransfer) GetSendToAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetRecipientAccount sets the "recipient" account.
func (inst *BridgeTransfer) SetRecipientAccount(recipient ag_solanago.PublicKey) *BridgeTransfer {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(recipient)
	return inst
}

// GetRecipientAccount gets the "recipient" account.
func (inst *BridgeTransfer) GetRecipientAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *BridgeTransfer) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *BridgeTransfer {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *BridgeTransfer) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

func (inst BridgeTransfer) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_BridgeTransfer,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst BridgeTransfer) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *BridgeTransfer) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.BridgeAuthority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SafeSettings is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.TokenMint is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.WhitelistedToken is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SendFrom is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SendTo is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Recipient is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *BridgeTransfer) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("BridgeTransfer")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Amount", *inst.Amount))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" bridgeAuthority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    safeSettings", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       tokenMint", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("whitelistedToken", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        sendFrom", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("          sendTo", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("       recipient", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("    tokenProgram", inst.AccountMetaSlice.Get(7)))
					})
				})
		})
}

func (obj BridgeTransfer) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	return nil
}
func (obj *BridgeTransfer) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	return nil
}

// NewBridgeTransferInstruction declares a new BridgeTransfer instruction with the provided parameters and accounts.
func NewBridgeTransferInstruction(
	// Parameters:
	amount uint64,
	// Accounts:
	bridgeAuthority ag_solanago.PublicKey,
	safeSettings ag_solanago.PublicKey,
	tokenMint ag_solanago.PublicKey,
	whitelistedToken ag_solanago.PublicKey,
	sendFrom ag_solanago.PublicKey,
	sendTo ag_solanago.PublicKey,
	recipient ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *BridgeTransfer {
	return NewBridgeTransferInstructionBuilder().
		SetAmount(amount).
		SetBridgeAuthorityAccount(bridgeAuthority).
		SetSafeSettingsAccount(safeSettings).
		SetTokenMintAccount(tokenMint).
		SetWhitelistedTokenAccount(whitelistedToken).
		SetSendFromAccount(sendFrom).
		SetSendToAccount(sendTo).
		SetRecipientAccount(recipient).
		SetTokenProgramAccount(tokenProgram)
}
