// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package tokens_safe

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RecoverLostFunds is the `recoverLostFunds` instruction.
type RecoverLostFunds struct {

	// [0] = [WRITE, SIGNER] adminAuthority
	//
	// [1] = [WRITE] safeSettings
	//
	// [2] = [WRITE] tokenMint
	//
	// [3] = [WRITE] whitelistedToken
	//
	// [4] = [WRITE] sendFrom
	//
	// [5] = [WRITE] sendTo
	//
	// [6] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRecoverLostFundsInstructionBuilder creates a new `RecoverLostFunds` instruction builder.
func NewRecoverLostFundsInstructionBuilder() *RecoverLostFunds {
	nd := &RecoverLostFunds{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 7),
	}
	return nd
}

// SetAdminAuthorityAccount sets the "adminAuthority" account.
func (inst *RecoverLostFunds) SetAdminAuthorityAccount(adminAuthority ag_solanago.PublicKey) *RecoverLostFunds {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(adminAuthority).WRITE().SIGNER()
	return inst
}

// GetAdminAuthorityAccount gets the "adminAuthority" account.
func (inst *RecoverLostFunds) GetAdminAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSafeSettingsAccount sets the "safeSettings" account.
func (inst *RecoverLostFunds) SetSafeSettingsAccount(safeSettings ag_solanago.PublicKey) *RecoverLostFunds {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(safeSettings).WRITE()
	return inst
}

// GetSafeSettingsAccount gets the "safeSettings" account.
func (inst *RecoverLostFunds) GetSafeSettingsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetTokenMintAccount sets the "tokenMint" account.
func (inst *RecoverLostFunds) SetTokenMintAccount(tokenMint ag_solanago.PublicKey) *RecoverLostFunds {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(tokenMint).WRITE()
	return inst
}

// GetTokenMintAccount gets the "tokenMint" account.
func (inst *RecoverLostFunds) GetTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetWhitelistedTokenAccount sets the "whitelistedToken" account.
func (inst *RecoverLostFunds) SetWhitelistedTokenAccount(whitelistedToken ag_solanago.PublicKey) *RecoverLostFunds {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(whitelistedToken).WRITE()
	return inst
}

// GetWhitelistedTokenAccount gets the "whitelistedToken" account.
func (inst *RecoverLostFunds) GetWhitelistedTokenAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSendFromAccount sets the "sendFrom" account.
func (inst *RecoverLostFunds) SetSendFromAccount(sendFrom ag_solanago.PublicKey) *RecoverLostFunds {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(sendFrom).WRITE()
	return inst
}

// GetSendFromAccount gets the "sendFrom" account.
func (inst *RecoverLostFunds) GetSendFromAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSendToAccount sets the "sendTo" account.
func (inst *RecoverLostFunds) SetSendToAccount(sendTo ag_solanago.PublicKey) *RecoverLostFunds {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(sendTo).WRITE()
	return inst
}

// GetSendToAccount gets the "sendTo" account.
func (inst *RecoverLostFunds) GetSendToAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *RecoverLostFunds) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *RecoverLostFunds {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *RecoverLostFunds) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

func (inst RecoverLostFunds) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RecoverLostFunds,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RecoverLostFunds) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RecoverLostFunds) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.AdminAuthority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SafeSettings is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.TokenMint is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.WhitelistedToken is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SendFrom is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SendTo is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *RecoverLostFunds) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RecoverLostFunds")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=7]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  adminAuthority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    safeSettings", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       tokenMint", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("whitelistedToken", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        sendFrom", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("          sendTo", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("    tokenProgram", inst.AccountMetaSlice.Get(6)))
					})
				})
		})
}

func (obj RecoverLostFunds) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *RecoverLostFunds) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewRecoverLostFundsInstruction declares a new RecoverLostFunds instruction with the provided parameters and accounts.
func NewRecoverLostFundsInstruction(
	// Accounts:
	adminAuthority ag_solanago.PublicKey,
	safeSettings ag_solanago.PublicKey,
	tokenMint ag_solanago.PublicKey,
	whitelistedToken ag_solanago.PublicKey,
	sendFrom ag_solanago.PublicKey,
	sendTo ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *RecoverLostFunds {
	return NewRecoverLostFundsInstructionBuilder().
		SetAdminAuthorityAccount(adminAuthority).
		SetSafeSettingsAccount(safeSettings).
		SetTokenMintAccount(tokenMint).
		SetWhitelistedTokenAccount(whitelistedToken).
		SetSendFromAccount(sendFrom).
		SetSendToAccount(sendTo).
		SetTokenProgramAccount(tokenProgram)
}
