// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package tokens_safe

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetBatchSlotLimit is the `setBatchSlotLimit` instruction.
type SetBatchSlotLimit struct {
	NewBatchSlotLimit *uint8

	// [0] = [WRITE, SIGNER] adminAuthority
	//
	// [1] = [WRITE] safeSettings
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetBatchSlotLimitInstructionBuilder creates a new `SetBatchSlotLimit` instruction builder.
func NewSetBatchSlotLimitInstructionBuilder() *SetBatchSlotLimit {
	nd := &SetBatchSlotLimit{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetNewBatchSlotLimit sets the "newBatchSlotLimit" parameter.
func (inst *SetBatchSlotLimit) SetNewBatchSlotLimit(newBatchSlotLimit uint8) *SetBatchSlotLimit {
	inst.NewBatchSlotLimit = &newBatchSlotLimit
	return inst
}

// SetAdminAuthorityAccount sets the "adminAuthority" account.
func (inst *SetBatchSlotLimit) SetAdminAuthorityAccount(adminAuthority ag_solanago.PublicKey) *SetBatchSlotLimit {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(adminAuthority).WRITE().SIGNER()
	return inst
}

// GetAdminAuthorityAccount gets the "adminAuthority" account.
func (inst *SetBatchSlotLimit) GetAdminAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSafeSettingsAccount sets the "safeSettings" account.
func (inst *SetBatchSlotLimit) SetSafeSettingsAccount(safeSettings ag_solanago.PublicKey) *SetBatchSlotLimit {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(safeSettings).WRITE()
	return inst
}

// GetSafeSettingsAccount gets the "safeSettings" account.
func (inst *SetBatchSlotLimit) GetSafeSettingsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst SetBatchSlotLimit) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetBatchSlotLimit,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetBatchSlotLimit) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetBatchSlotLimit) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.NewBatchSlotLimit == nil {
			return errors.New("NewBatchSlotLimit parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.AdminAuthority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SafeSettings is not set")
		}
	}
	return nil
}

func (inst *SetBatchSlotLimit) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetBatchSlotLimit")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("NewBatchSlotLimit", *inst.NewBatchSlotLimit))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("adminAuthority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("  safeSettings", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj SetBatchSlotLimit) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `NewBatchSlotLimit` param:
	err = encoder.Encode(obj.NewBatchSlotLimit)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetBatchSlotLimit) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `NewBatchSlotLimit`:
	err = decoder.Decode(&obj.NewBatchSlotLimit)
	if err != nil {
		return err
	}
	return nil
}

// NewSetBatchSlotLimitInstruction declares a new SetBatchSlotLimit instruction with the provided parameters and accounts.
func NewSetBatchSlotLimitInstruction(
	// Parameters:
	newBatchSlotLimit uint8,
	// Accounts:
	adminAuthority ag_solanago.PublicKey,
	safeSettings ag_solanago.PublicKey) *SetBatchSlotLimit {
	return NewSetBatchSlotLimitInstructionBuilder().
		SetNewBatchSlotLimit(newBatchSlotLimit).
		SetAdminAuthorityAccount(adminAuthority).
		SetSafeSettingsAccount(safeSettings)
}
