// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package tokens_safe

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// TransferBridge is the `transferBridge` instruction.
type TransferBridge struct {
	BridgeAuthority *ag_solanago.PublicKey

	// [0] = [WRITE, SIGNER] adminAuthority
	//
	// [1] = [WRITE] safeSettings
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewTransferBridgeInstructionBuilder creates a new `TransferBridge` instruction builder.
func NewTransferBridgeInstructionBuilder() *TransferBridge {
	nd := &TransferBridge{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetBridgeAuthority sets the "bridgeAuthority" parameter.
func (inst *TransferBridge) SetBridgeAuthority(bridgeAuthority ag_solanago.PublicKey) *TransferBridge {
	inst.BridgeAuthority = &bridgeAuthority
	return inst
}

// SetAdminAuthorityAccount sets the "adminAuthority" account.
func (inst *TransferBridge) SetAdminAuthorityAccount(adminAuthority ag_solanago.PublicKey) *TransferBridge {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(adminAuthority).WRITE().SIGNER()
	return inst
}

// GetAdminAuthorityAccount gets the "adminAuthority" account.
func (inst *TransferBridge) GetAdminAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSafeSettingsAccount sets the "safeSettings" account.
func (inst *TransferBridge) SetSafeSettingsAccount(safeSettings ag_solanago.PublicKey) *TransferBridge {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(safeSettings).WRITE()
	return inst
}

// GetSafeSettingsAccount gets the "safeSettings" account.
func (inst *TransferBridge) GetSafeSettingsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst TransferBridge) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_TransferBridge,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst TransferBridge) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *TransferBridge) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.BridgeAuthority == nil {
			return errors.New("BridgeAuthority parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.AdminAuthority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SafeSettings is not set")
		}
	}
	return nil
}

func (inst *TransferBridge) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("TransferBridge")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("BridgeAuthority", *inst.BridgeAuthority))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("adminAuthority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("  safeSettings", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj TransferBridge) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `BridgeAuthority` param:
	err = encoder.Encode(obj.BridgeAuthority)
	if err != nil {
		return err
	}
	return nil
}
func (obj *TransferBridge) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `BridgeAuthority`:
	err = decoder.Decode(&obj.BridgeAuthority)
	if err != nil {
		return err
	}
	return nil
}

// NewTransferBridgeInstruction declares a new TransferBridge instruction with the provided parameters and accounts.
func NewTransferBridgeInstruction(
	// Parameters:
	bridgeAuthority ag_solanago.PublicKey,
	// Accounts:
	adminAuthority ag_solanago.PublicKey,
	safeSettings ag_solanago.PublicKey) *TransferBridge {
	return NewTransferBridgeInstructionBuilder().
		SetBridgeAuthority(bridgeAuthority).
		SetAdminAuthorityAccount(adminAuthority).
		SetSafeSettingsAccount(safeSettings)
}
